#define global ARGS_SCALAR double,double,double,double
#define global ARGS_LONG int,int
#define global ARGS_SIZE int,int
#define global ARGS_TERMCRITERIA int,int,double
#define global ARGS_RECT int,int,int,int
#define global ARGS_POINT3D double,double,double
#define global ARGS_ULONG int,int
#define global ARGS_POINT2D double,double
#define global ARGS_RANGE int,int
#define global ARGS_KEYPOINT float,float,float,float,float,int,int
#define global ARGS_DMATCH int,int,int,float
#define global ARGS_POINT int,int
#define global ARGS_POINT2F float,float
#define global ARGS_POINT3I int,int,int
#define global ARGS_POINT3F float,float,float
#define global ARGS_SIZE2F float,float
#define global ARGS_SIZE2D double,double
#define global ARGS_RECT2F float,float,float,float
#define global ARGS_RECT2D double,double,double,double
#define global ARGS_VEC2I int,int
#define global ARGS_VEC3I int,int,int
#define global ARGS_VEC4I int,int,int,int
#define global ARGS_VEC6I int,int,int,int,int,int
#define global ARGS_VEC2D double,double
#define global ARGS_VEC3D double,double,double
#define global ARGS_VEC4D double,double,double,double
#define global ARGS_VEC6D double,double,double,double,double,double
#define global ARGS_VEC2F float,float
#define global ARGS_VEC3F float,float,float
#define global ARGS_VEC4F float,float,float,float
#define global ARGS_VEC6F float,float,float,float,float,float
#define global ARGS_VEC2B int
#define global ARGS_VEC3B int
#define global ARGS_VEC4B int
#define global ARGS_VEC6B int,int
#define global ARGS_VEC2S int
#define global ARGS_VEC3S int,int
#define global ARGS_VEC4S int,int
#define global ARGS_VEC6S int,int,int
#define global ARGS_VEC2W int
#define global ARGS_VEC3W int,int
#define global ARGS_VEC4W int,int
#define global ARGS_VEC6W int,int,int
#define global ARGS_ROTATEDRECT float,float,float,float,float
#define global ARGS_TRACKERKCF_PARAMS float,float,float,float,float,float,int,int,int,int,int
